language: c

compiler:
  - clang
  - gcc

script:
  - make
  - sudo make install; sudo ldconfig
  - make clean; make amtoy1; ./amtoy1 -f myout
  - test -f myout_mix.data
  - ./amtoy1 -m 1 -N 1000 -b 100 -f myout
  - test -f myout_k.data
  - rm myout*.data; rm libautomix.so
  - make clean; make amtoy1 DEBUG=1; ./amtoy1 -N 1000
  - test -f output_mix.data
  - rm output_*.data;
  - make clean; make tutorial; ./tutorial
  - make clean; make test; ./test
  - clang-format src/user_examples/main.c | diff - src/user_examples/main.c
  - clang-format src/libautomix/automix.c | diff - src/libautomix/automix.c
  - clang-format src/libautomix/automix.h | diff - src/libautomix/automix.h
  - clang-format src/user_examples/logwrite.c | diff - src/user_examples/logwrite.c
  - clang-format src/user_examples/logwrite.h | diff - src/user_examples/logwrite.h
  - clang-format src/user_examples/tutorial.c | diff - src/user_examples/tutorial.c
  - clang-format tests/test_automix.c | diff - tests/test_automix.c
