language: c

compiler:
  - clang
  - gcc

script:
  - make amtoy1 amtoy2
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - ./amtoy1
  - test -f output_mix.data
  - ./amtoy1 -m 1 -N 1000
  - ./amtoy2 -f myout
  - test -f myout_mix.data
  - ./amtoy2 -m 1 -f myout -N 1000
  - make clean; rm output_*.data myout*.data; rm libautomix.so
  - make amtoy1 amtoy2 DEBUG=1
  - ./amtoy1 -N 1000
  - test -f output_mix.data
  - clang-format src/user_examples/main.c | diff - src/user_examples/main.c
  - clang-format src/libautomix/automix.c | diff - src/libautomix/automix.c
  - clang-format src/libautomix/automix.h | diff - src/libautomix/automix.h
  - clang-format src/libautomix/logwrite.c | diff - src/libautomix/logwrite.c
  - clang-format src/libautomix/logwrite.h | diff - src/libautomix/logwrite.h
  - clang-format tests/main.c | diff - tests/main.c
  - make clean
  - make test
  - ./test
