language: c

compiler:
  - clang
  - gcc

script:
  - make all
  - ./amtoy1
  - ./amtoy1 -m 1
  - ./amtoy2
  - ./amtoy2 -m 1
  - make clean
  - rm output_*.data
  - make alldebug
  - ./amtoy1d
  - ./amtoy1d -m 1
  - ./amtoy2d
  - ./amtoy2d -m 1
