language: c

compiler:
  - clang
  - gcc

script:
  - make
  - ./amtoy1
  - test -f output_mix.data
  - ./amtoy1 -m 1 -N 1000
  - ./amtoy2 -f myout
  - test -f myout_mix.data
  - ./amtoy2 -m 1 -f myout -N 1000
  - make clean
  - rm output_*.data myout*.data
  - make DEBUG=1
  - ./amtoy1 -N 1000
  - test -f output_mix.data
  - make clean
  - clang-format main.c | diff - main.c
  - clang-format automix.c | diff - automix.c
  - clang-format automix.h | diff - automix.h
  - clang-format logwrite.c | diff - logwrite.c
  - clang-format logwrite.h | diff - logwrite.h
